version: '3'

# docker compose for local runs only. Contains unprotected databases
services:
  postgres:
    container_name: postgres
    image: postgres:14.5
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=sayan
      - POSTGRES_DB=demo